### PR TITLE
Allow Android build

### PR DESCRIPTION
**Pull request by MajliTech**
We cannot build on Termux without this, however Android is on Linux so this is fine.

### CODE REVIEW

**Comment by grafin** [comment]
Does it build and run after with this patch?

**Comment by MajliTech** [comment]
Not yet, complains about not finding mqueue.h, despite existing
```
$ file /data/data/com.termux/files/usr/include/linux/mqueue.h
/data/data/com.termux/files/usr/include/linux/mqueue.h: C source, ASCII text
```

**Comment by 0x501D** [comment]
> Not yet, complains about not finding mqueue.h, despite existing
> 
> ```
> $ file /data/data/com.termux/files/usr/include/linux/mqueue.h
> /data/data/com.termux/files/usr/include/linux/mqueue.h: C source, ASCII text
> ```

Apparently for android you need to throw additional includes in cmake. In any case, CI has not yet passed. It is necessary to bring the commit message in accordance with the format accepted in this repository. Also something went wrong on FreeBSD.

**Comment by MajliTech** [comment]
Closing, will create another commit with the style.

**Comment by 0x501D** [comment]
> Closing, will create another commit with the style.

It is not necessary to close the pull request. You can make edits with the second commit, then interactively rebase (`git rebase -i HEAD~2`) with a fixup of this commit into the first one and force push.

**Pull request closed without merging**
